<?php
require_once __DIR__ . '/auth.php'; require_once __DIR__ . '/RecipeModel.php'; requireLogin(); $model = new Recipe(); $errors = [];
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $title=trim((string)($_POST['title']??'')); $description=trim((string)($_POST['description']??'')); $steps=trim((string)($_POST['steps']??'')); $category=(int)($_POST['category_id']??0);
    $ingredients=array_values(array_filter(array_map('trim', (array)($_POST['ingredients']??[]))));
    if (!verifyCsrf($_POST['csrf_token']??null)) $errors[]='Your session expired.'; if ($title===''||strlen($title)>255) $errors[]='Enter a recipe title up to 255 characters.'; if ($description===''||$steps==='') $errors[]='Description and steps are required.'; if ($category<1||!$ingredients) $errors[]='Choose a category and add at least one ingredient.';
    if (!$errors) { try { $id=$model->createRecipe(currentUserId(),$category,$title,$description,$steps,$ingredients); header("Location: recipe.php?id=$id"); exit; } catch (Throwable $exception) { $errors[]='The recipe could not be saved.'; } }
}
$categories=$model->categories(); $pageTitle='Share a recipe'; require __DIR__.'/header.php';
?><section class="panel form-panel"><h1>Share a family recipe</h1><?php foreach($errors as $error): ?><p class="error"><?=e($error)?></p><?php endforeach; ?><form id="recipe-form" method="post"><input type="hidden" name="csrf_token" value="<?=e(csrfToken())?>"><div class="form-group"><label for="title">Recipe title</label><input class="form-control" id="title" name="title" maxlength="255" required value="<?=e($_POST['title']??'')?>"></div><div class="form-group"><label for="category_id">Category</label><select class="form-control" id="category_id" name="category_id" required><option value="">Choose one</option><?php foreach($categories as $category): ?><option value="<?=e($category['id'])?>"><?=e($category['name'])?></option><?php endforeach; ?></select></div><div class="form-group"><label for="description">Short description</label><textarea class="form-control" id="description" name="description" required><?=e($_POST['description']??'')?></textarea></div><div class="form-group"><label>Ingredients</label><div id="ingredients"><div class="ingredient-row"><input class="form-control" name="ingredients[]" required placeholder="e.g. 500g chicken"><button class="btn btn-danger remove-ingredient" type="button">Remove</button></div></div><button class="btn btn-secondary" id="add-ingredient" type="button">+ Add ingredient</button></div><div class="form-group"><label for="steps">Cooking steps</label><textarea class="form-control" id="steps" name="steps" required><?=e($_POST['steps']??'')?></textarea></div><button class="btn" type="submit">Publish recipe</button></form></section><?php require __DIR__.'/footer.php'; ?>
