<?php
require_once __DIR__ . '/auth.php'; require_once __DIR__ . '/RecipeModel.php'; requireLogin(); $model = new Recipe(); $id = filter_input(INPUT_GET, 'id', FILTER_VALIDATE_INT); $recipe = $id ? $model->getRecipeWithIngredients($id, currentUserId()) : null;
if (!$recipe || (int) $recipe['user_id'] !== currentUserId()) { http_response_code(403); exit('You cannot edit this recipe.'); }
$errors = [];
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $title=trim((string)($_POST['title']??'')); $description=trim((string)($_POST['description']??'')); $steps=trim((string)($_POST['steps']??'')); $category=(int)($_POST['category_id']??0); $ingredients=array_values(array_filter(array_map('trim',(array)($_POST['ingredients']??[]))));
    if (!verifyCsrf($_POST['csrf_token']??null)) $errors[]='Your session expired.'; if ($title===''||$description===''||$steps===''||$category<1||!$ingredients) $errors[]='All fields and at least one ingredient are required.';
    if (!$errors) { try { $model->updateRecipe($id,currentUserId(),$category,$title,$description,$steps,$ingredients); header("Location: recipe.php?id=$id"); exit; } catch(Throwable $exception) { $errors[]='The recipe could not be updated.'; } }
}
$categories=$model->categories(); $pageTitle='Edit recipe'; require __DIR__.'/header.php'; ?>
<section class="panel form-panel"><h1>Edit recipe</h1><?php foreach($errors as $error):?><p class="error"><?=e($error)?></p><?php endforeach;?><form method="post"><input type="hidden" name="csrf_token" value="<?=e(csrfToken())?>"><div class="form-group"><label>Title</label><input class="form-control" name="title" maxlength="255" required value="<?=e($_POST['title']??$recipe['title'])?>"></div><div class="form-group"><label>Category</label><select class="form-control" name="category_id" required><?php foreach($categories as $category):?><option value="<?=e($category['id'])?>" <?=((int)($category['id'])===(int)($_POST['category_id']??$recipe['category_id']))?'selected':''?>><?=e($category['name'])?></option><?php endforeach;?></select></div><div class="form-group"><label>Description</label><textarea class="form-control" name="description" required><?=e($_POST['description']??$recipe['description'])?></textarea></div><div class="form-group"><label>Ingredients</label><?php $savedIngredients=$_POST['ingredients']??array_column($recipe['ingredients'],'ingredient_name');foreach($savedIngredients as $ingredient):?><div class="ingredient-row"><input class="form-control" name="ingredients[]" required value="<?=e($ingredient)?>"></div><?php endforeach;?></div><div class="form-group"><label>Cooking steps</label><textarea class="form-control" name="steps" required><?=e($_POST['steps']??$recipe['steps'])?></textarea></div><button class="btn" type="submit">Save changes</button></form></section><?php require __DIR__.'/footer.php';?>
